### ISSUE TITLE
Algorithm description is missing from function documentation

### ISSUE THREAD

**Issue by florisvdh** [JanCaha/r_package_qgis#38]
The algorithm functions' description currently contain following type of information, e.g. for `native:centroids`:

> QGIS Algorithm provided by QGIS (native c++) Centroids (native:centroids)

But the actual algorithm description is missing. It is what `qgisprocess::qgis_get_description("native:centroids")` provides, so this is preferably added.

**Comment by JanCaha** [comment]
@florisvdh would you mind checking this https://github.com/JanCaha/r_package_qgis/actions/runs/5398098934/jobs/9803506195 workflow? I did some updates, amongst them the issue reference here and wanted to update the workflow a bit. I borrowed a lot of the steps directly from qgisprocess workflow but I am still getting this weird error
```
unable to load shared object '/home/runner/work/_temp/Library/stringi/libs/stringi.so':
  libicui18n.so.66: cannot open shared object file: No such file or directory
```
which causes the whole wf to fail. 

Any ideas what might be wrong?

**Comment by florisvdh** [comment]
Not sure, but at least something seems going to be wrong with the stringi/stringr installation. Also there is some duplication caused by the step (e.g. triggering another stringr installation):

      - name: Install remotes and package build dependencies
        run: source("./build-package/install_save_deps.R")
        shell: Rscript {0}

I wonder whether you could drop this step, and transfer the packages from `install_save_deps.R` to the `pak::install()` step before (at least that should also deal with the duplication). No idea whether it would solve the issue though.

The error is about a missing file `libicui18n.so.66`, but that is only installed by libicu66 in Ubuntu 20.04, not by the current libicu70 in Ubuntu 22.04, which provides `libicui18n.so.70`. Do you still have some reference to R packages from Ubuntu 20.04?

**Comment by JanCaha** [comment]
Thanks for the tips. Seems like moving all the packages installs to pak solved the issue. The latest version of the package is generating now and should be available in hour or something :+1:

**Comment by florisvdh** [comment]
Hi @JanCaha, following line needs to use `jammy/latest` instead of `focal/latest`:

https://github.com/JanCaha/r_package_qgis/blob/0b2bb1f00162d0e2fb50e0dfd8497fb083f5ebae/.github/workflows/build_package.yaml#L22

**Comment by JanCaha** [comment]
Fixed and finally working. Seems like a lot of changes in qgisprocess and infrastructure accumulated and cause quite a lot of troubles ...
